/**
 * Generates the decision-engine source that is embedded into every `route` step.
 *
 * The whole point of generating rather than hand-writing this: the precedence order,
 * the matcher semantics and the audit record are IDENTICAL in every workflow in the
 * estate, because they come from one generator. A hand-written router in each workflow
 * is how "the system decided" becomes unanswerable.
 */
export function buildResolverSource({ tag, routing, verticals }) {
  const bindings = Object.fromEntries(
    Object.entries(verticals).map(([id, v]) => [id, v.capability_bindings ?? {}])
  );

  const policy = {
    precedence: routing.precedence,
    hard_rules: routing.hard_rules ?? [],
    policy_table: (routing.policy_table ?? []).filter((r) => r.tag === tag),
    defaults: routing.defaults ?? {},
    gray_zone: routing.gray_zone ?? {},
  };

  return `// GENERATED by compiler/router.mjs — do not edit in the n8n canvas.
// Resolves the abstract capability tag "${tag}" to a concrete implementation.
// Precedence: ${policy.precedence.join(' -> ')}
const TAG = ${JSON.stringify(tag)};
const POLICY = ${JSON.stringify(policy, null, 2)};
const VERTICAL_BINDINGS = ${JSON.stringify(bindings, null, 2)};

const env = $('Envelope In').first().json;
const brief = env.payload?.brief ?? $json.brief ?? {};
const context = { ...(env.payload?.context ?? {}), ...($json.context ?? {}), ...$json };

function readPath(path) {
  // Supports "a.b.c" and "a.b[].c" (the latter collects across an array).
  const parts = path.split('.');
  let scope = parts.shift();
  let cur = scope === 'envelope' ? env : scope === 'brief' ? brief : scope === 'context' ? context : undefined;
  for (const raw of parts) {
    if (cur == null) return undefined;
    if (raw.endsWith('[]')) {
      const key = raw.slice(0, -2);
      const arr = cur[key];
      if (!Array.isArray(arr)) return undefined;
      cur = arr;
      continue;
    }
    cur = Array.isArray(cur) ? cur.map(x => x?.[raw]).filter(v => v !== undefined) : cur[raw];
  }
  return cur;
}

function resolveRef(v) {
  return (typeof v === 'string' && v.startsWith('@')) ? readPath(v.slice(1)) : v;
}

// Policy authors write PCRE-style inline flags ((?i)...) which JS RegExp rejects outright.
// Translating them here rather than forbidding them keeps the rule files readable; the
// validator compiles every pattern at build time so a genuinely broken one fails the build
// instead of silently never matching a compliance rule.
function toRegExp(pattern) {
  const m = /^\\(\\?([imsux]+)\\)/.exec(pattern);
  if (!m) return new RegExp(pattern);
  const flags = m[1].replace(/[xu]/g, '');
  return new RegExp(pattern.slice(m[0].length), flags);
}

function test(actual, op, expected) {
  const exp = resolveRef(expected);
  switch (op) {
    case 'eq': return actual === exp;
    case 'neq': return actual !== exp;
    case 'in': return Array.isArray(exp) && exp.includes(actual);
    case 'nin': return Array.isArray(exp) && !exp.includes(actual);
    case 'gt': return Number(actual) > Number(exp);
    case 'gte': return Number(actual) >= Number(exp);
    case 'lt': return Number(actual) < Number(exp);
    case 'lte': return Number(actual) <= Number(exp);
    case 'exists': return (actual !== undefined && actual !== null) === Boolean(exp);
    case 'matches': return toRegExp(exp).test(String(actual ?? ''));
    case 'any_of': {
      const arr = Array.isArray(actual) ? actual : [actual];
      return Array.isArray(exp) && arr.some(a => exp.includes(a));
    }
    default: return false;
  }
}

function matches(when) {
  if (!when || Object.keys(when).length === 0) return true;
  return Object.entries(when).every(([path, cond]) =>
    Object.entries(cond).every(([op, expected]) => test(readPath(path), op, expected))
  );
}

const decision = {
  decision_id: 'dec_' + (env.trace_id ?? 'x').slice(4, 16) + '_' + TAG.replace(/\\./g, '_'),
  trace_id: env.trace_id,
  tenant_id: env.tenant_id,
  vertical: env.vertical ?? 'generic',
  kind: 'capability_binding',
  question: 'Which implementation satisfies ' + TAG + '?',
  options: [],
  at: new Date().toISOString()
};

let resolved = null, by = null, ruleId = null, vetoed = null;
const constraints = [];

for (const layer of POLICY.precedence) {
  if (resolved || vetoed) break;

  if (layer === 'hard_rule') {
    for (const rule of POLICY.hard_rules) {
      if (!matches(rule.when)) continue;
      decision.options.push({ value: rule.id, eliminated_by: null });
      const act = rule.then.action;
      if (act === 'veto') { vetoed = rule; break; }
      if (act === 'bind') { resolved = rule.then.capability; by = 'hard_rule'; ruleId = rule.id; break; }
      // require_approval / downgrade_autonomy / force_provider / add_step do not BIND —
      // they constrain the run and are carried forward for the orchestrator to honour.
      constraints.push({ rule_id: rule.id, action: act, reason_code: rule.then.reason_code, message: rule.then.message ?? null });
    }
  }

  if (layer === 'vertical_binding' && !resolved) {
    const bound = VERTICAL_BINDINGS[env.vertical ?? 'generic']?.[TAG];
    if (bound) { resolved = bound; by = 'vertical_binding'; ruleId = (env.vertical ?? 'generic') + ':' + TAG; }
  }

  if (layer === 'policy_table' && !resolved) {
    for (const row of POLICY.policy_table) {
      if (!matches(row.when)) { decision.options.push({ value: row.bind, eliminated_by: 'policy_table_condition' }); continue; }
      resolved = row.bind; by = 'policy_table'; ruleId = row.note ?? null; break;
    }
  }

  if (layer === 'default' && !resolved) {
    const d = POLICY.defaults[TAG];
    if (d) { resolved = d; by = 'default'; }
  }
}

if (vetoed) {
  return [{ json: {
    resolved_capability: null,
    vetoed: true,
    decision: { ...decision, chosen: 'VETO:' + vetoed.id, decided_by: 'hard_rule', rule_id: vetoed.id, rationale: vetoed.then.message ?? vetoed.description ?? 'Blocked by a hard rule.' },
    error: { code: vetoed.then.reason_code === 'BUDGET_EXCEEDED' ? 'BUDGET_EXCEEDED' : 'POLICY_BLOCKED', message: vetoed.then.message ?? vetoed.id, retryable: false, at: new Date().toISOString() }
  } }];
}

if (!resolved) {
  throw new Error('INTERNAL: no implementation resolved for tag ' + TAG + ' and no default is declared. This is a build-time error that escaped the validator.');
}

return [{ json: {
  ...$json,
  resolved_capability: resolved,
  routing: { requested_capability: TAG, resolved_capability: resolved, implementation: resolved, binding_source: by, decision_id: decision.decision_id },
  constraints,
  decision: { ...decision, chosen: resolved, decided_by: by, rule_id: ruleId, rationale: 'Bound by ' + by + (ruleId ? ' (' + ruleId + ')' : '') + '.' }
} }];
`;
}
