#!/usr/bin/env node
/**
 * Prints the estate as a dependency graph and emits a Mermaid diagram to docs/.
 * Useful for the question nobody can answer from a folder of n8n canvases:
 * "if I change this terminal, what breaks?"
 */
import fs from 'node:fs';
import path from 'node:path';
import { loadSpecs, loadRegistry, ROOT } from '../compiler/load.mjs';

const specs = loadSpecs();
const registry = loadRegistry();

const edges = new Map();
for (const [id, spec] of specs) {
  const out = new Set(spec.capability.requires?.capabilities ?? []);
  for (const step of spec.n8n.nodes ?? []) {
    const t = step.with?.capability;
    if (step.kind === 'call' && typeof t === 'string' && !t.startsWith('=')) out.add(t);
    for (const tool of step.with?.tools ?? []) out.add(tool);
  }
  edges.set(id, [...out]);
}

const dependents = new Map();
for (const [from, tos] of edges) for (const to of tos) dependents.set(to, [...(dependents.get(to) ?? []), from]);

const arg = process.argv[2];
if (arg) {
  const seen = new Set();
  const walk = (id, depth) => {
    if (depth > 6 || seen.has(id)) return;
    seen.add(id);
    console.log('  '.repeat(depth) + (depth ? '└─ ' : '') + id + (specs.has(id) ? '' : '  (roadmap)'));
    for (const d of edges.get(id) ?? []) walk(d, depth + 1);
  };
  console.log(`\ndependencies of ${arg}:`);
  walk(arg, 0);
  console.log(`\ndependents (things that break if ${arg} changes):`);
  for (const d of dependents.get(arg) ?? []) console.log('  ' + d);
  if (!(dependents.get(arg) ?? []).length) console.log('  (none — this is a leaf)');
  process.exit(0);
}

const byLayer = { system: [], subsystem: [], terminal: [] };
for (const [id, spec] of specs) byLayer[spec.capability.layer].push(id);

console.log('\nESTATE');
for (const layer of ['system', 'subsystem', 'terminal']) {
  console.log(`\n  ${layer} (${byLayer[layer].length})`);
  for (const id of byLayer[layer].sort()) {
    const c = specs.get(id).capability;
    const deps = (edges.get(id) ?? []).length;
    const users = (dependents.get(id) ?? []).length;
    console.log(`    ${id.padEnd(38)} ${String(c.side_effects).padEnd(15)} deps:${String(deps).padEnd(3)} used-by:${users}`);
  }
}

const hot = [...dependents.entries()].sort((a, b) => b[1].length - a[1].length).slice(0, 8);
console.log('\n  most depended-upon (change these carefully):');
for (const [id, users] of hot) console.log(`    ${id.padEnd(38)} ${users.length} dependents`);

const mermaid = [
  '```mermaid',
  'graph LR',
  '  classDef system fill:#1f2937,stroke:#6366f1,color:#fff',
  '  classDef subsystem fill:#1e3a5f,stroke:#38bdf8,color:#fff',
  '  classDef terminal fill:#14532d,stroke:#4ade80,color:#fff',
];
const nodeId = (id) => id.replace(/[.]/g, '_');
for (const [id, spec] of specs) {
  if (spec.capability.layer === 'terminal' && !(dependents.get(id) ?? []).length) continue; // keep it readable
  mermaid.push(`  ${nodeId(id)}["${spec.capability.title}"]:::${spec.capability.layer}`);
}
for (const [from, tos] of edges) {
  if (!specs.has(from)) continue;
  for (const to of tos) {
    if (!specs.has(to)) continue;
    if (specs.get(to).capability.layer === 'terminal' && !(dependents.get(to) ?? []).length) continue;
    mermaid.push(`  ${nodeId(from)} --> ${nodeId(to)}`);
  }
}
mermaid.push('```');
fs.writeFileSync(path.join(ROOT, 'docs', 'estate-graph.md'),
  `# Estate graph\n\nGenerated by \`npm run graph\`. Terminal capabilities with no dependents are omitted to keep the diagram readable — see \`dist/capabilities.json\` for the complete list.\n\n${mermaid.join('\n')}\n`);
console.log('\n  wrote docs/estate-graph.md');
